services:
  tsusi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/home/bun/app/node_modules
      - ../:/home/bun/app:cached
    tty: true
    stdin_open: true

volumes:
  node_modules:
